version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: ielts_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ielts_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql+pymysql://admin:admin123@mysql:3306/ielts_db"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  mysql_data:
